title = "Future"
gitSourceBranch = "main"

apiCategories = [
	"Constructors",
	"Static Methods",
	"Methods"
]

[home]
enabled = false
includeReadme = true

[docusaurus.themeConfig.colorMode]
respectPrefersColorScheme = true
defaultMode = "dark"