[package]
name = "egomoose/future"
description = "A simple future class used as an abstraction for defining eventual values that result from asynchronous computations."
repository = "https://github.com/EgoMoose/future-luau"
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
Signal = "sleitnick/signal@2.0.3"